export const SET_SCORE = 'set score'
export const INCREMENT_SCORE = 'increment score'
export const SET_LINES = 'set lines'
export const INCREMENT_LINES = 'increment lines'
export const SET_LEVEL = 'set level'
export const RESET_SCORE = 'reset score'
